export class companyRegistration{
    id!: string;
    firstname!: string;   
    lastname!: string;
    userName!: string;
    email!: string;
    password!: string;
    phone!: string;
   // profilePicture!: string;
    // status!: boolean;
    adress!: string;
    organizationAddress!: string;
    organizationName!: string;
    organizationEmail!: string;
    organizationPhone!: string;

    // createdDate!: string;
    // updatedDate!: string;
}